const languages = {
    ko: {
        // Auth
        'login_fail': '사용자 이름 또는 비밀번호가 올바르지 않습니다.',
        'register_success': '회원가입이 완료되었습니다. 이제 로그인해주세요.',
        'username_exists': '이미 존재하는 사용자 이름입니다.',
        'enter_username_password': '사용자 이름과 비밀번호를 모두 입력해주세요.',

        // Game
        'job': '직업',
        'warrior': '검사',
        'mage': '마법사',
        'priest': '성직자',
        'thief': '도적',
        'no_job': '무직',
        'level': '레벨',
        'exp': '경험치',
        'hp': '체력',
        'mana': '마나',
        'ultimate': '궁극기',
        'gold': '골드',
        'potions': '물약',
        'game_over': '게임 오버',
        'death_penalty': '쓰러졌습니다! 경험치 10%를 잃고 마을로 돌아왔습니다.',
        'no_mana': '마나가 부족합니다!',
        'no_ultimate': '궁극기 게이지가 부족합니다!',
        'already_have_job': '이미 직업이 있습니다.',
        'need_level_3_for_job': '레벨 3 이상만 전직할 수 있습니다.',
        'need_50_gold_for_job': '전직하려면 50골드가 필요합니다.',
        'job_change_complete': '전직 완료! 당신은 이제 \'{job}\'입니다!',
        'job_reset_confirm': '정말로 50골드를 지불하고 직업을 초기화하시겠습니까?',
        'job_reset_complete': '직업이 초기화되었습니다.',
        'need_job_for_skill': '먼저 전직을 해야 스킬을 배울 수 있습니다.',
        'not_enough_gold': '골드가 부족합니다.',
        'already_learned_skill': '이미 해당 종류의 스킬을 배웠습니다.',
        'skill_learned': '\'{skillName}\' 스킬을 배웠습니다!',
        'no_potions': '보유한 물약이 없습니다.',
        'hp_full': 'HP가 이미 가득 찼습니다!',
        'mana_full': '마나가 이미 가득 찼습니다!',
        'hp_and_mana_full': 'HP와 마나가 모두 가득 찼습니다!',
        'use': '사용',
        'in_possession': '보유중',
        'learn': '배우기',
        'already_have_weapon': '이미 해당 직업의 무기를 소지하고 있습니다. 먼저 판매하거나 다른 무기를 선택하세요.',
        'job_restricted_item': '이 아이템은 \'{job}\' 직업만 구매할 수 있습니다.',
        'item_purchased_attack_increase': '\'{itemName}\'을(를) 구매했습니다! 공격력이 \'{attack}\' 증가했습니다.',
        'item_purchased': '\'{itemName}\'을(를) 구매했습니다!',

        // NPCs
        'merchant': '상인',
        'job_master': '전직관',
        'skill_master': '스킬관',
        'reset_master': '삭제관',

        // Portals
        'slime_dungeon': '슬라임 동굴',
        'goblin_dungeon': '고블린 동굴',
        'orc_dungeon': '오크 동굴',
        'subspecies_dungeon': '아종의 동굴',
        'exit': '출구',

        // UI
        'settings': '설정',
        'keybinds': '키 설정',
        'up': '위로',
        'down': '아래로',
        'left': '왼쪽',
        'right': '오른쪽',
        'attack': '공격',
        'interact': '상호작용',
        'potion': '물약',
        'weak_skill': '약한 스킬',
        'strong_skill': '강한 스킬',
        'ultimate_skill': '궁극기',
        'left_click': '좌클릭',
        'right_click': '우클릭',
        'key_in_use': '이미 사용 중인 키입니다!',
        'already_in_town': '이미 마을에 있습니다.',
    },
    en: {
        // Auth
        'login_fail': 'Invalid username or password.',
        'register_success': 'Registration successful. Please log in.',
        'username_exists': 'Username already exists.',
        'enter_username_password': 'Please enter both username and password.',

        // Game
        'job': 'Job',
        'warrior': 'Warrior',
        'mage': 'Mage',
        'priest': 'Priest',
        'thief': 'Thief',
        'no_job': 'Unemployed',
        'level': 'Level',
        'exp': 'EXP',
        'hp': 'HP',
        'mana': 'Mana',
        'ultimate': 'Ultimate',
        'gold': 'Gold',
        'potions': 'Potions',
        'game_over': 'Game Over',
        'death_penalty': 'You fell! You lost 10% of your EXP and returned to the village.',
        'no_mana': 'Not enough mana!',
        'no_ultimate': 'Ultimate gauge is not full!',
        'already_have_job': 'You already have a job.',
        'need_level_3_for_job': 'You must be level 3 or higher to change jobs.',
        'need_50_gold_for_job': 'You need 50 gold to change jobs.',
        'job_change_complete': 'Job change complete! You are now a \'{job}\'!',
        'job_reset_confirm': 'Are you sure you want to pay 50 gold to reset your job?',
        'job_reset_complete': 'Your job has been reset.',
        'need_job_for_skill': 'You must get a job before you can learn skills.',
        'not_enough_gold': 'Not enough gold.',
        'already_learned_skill': 'You have already learned this type of skill.',
        'skill_learned': 'You have learned the \'{skillName}\' skill!',
        'no_potions': 'You have no potions.',
        'hp_full': 'HP is already full!',
        'mana_full': 'Mana is already full!',
        'hp_and_mana_full': 'HP and Mana are both full!',
        'use': 'Use',
        'in_possession': 'Owned',
        'learn': 'Learn',
        'already_have_weapon': 'You already have a weapon for this job. Please sell it first or choose another weapon.',
        'job_restricted_item': 'This item can only be purchased by the \'{job}\' job.',
        'item_purchased_attack_increase': 'You have purchased \'{itemName}\'! Attack power has increased by \'{attack}\'.',
        'item_purchased': 'You have purchased \'{itemName}\'!',

        // NPCs
        'merchant': 'Merchant',
        'job_master': 'Job Master',
        'skill_master': 'Skill Master',
        'reset_master': 'Reset Master',

        // Portals
        'slime_dungeon': 'Slime Cave',
        'goblin_dungeon': 'Goblin Cave',
        'orc_dungeon': 'Orc Cave',
        'subspecies_dungeon': 'Subspecies Cave',
        'exit': 'Exit',

        // UI
        'settings': 'Settings',
        'keybinds': 'Keybinds',
        'up': 'Up',
        'down': 'Down',
        'left': 'Left',
        'right': 'Right',
        'attack': 'Attack',
        'interact': 'Interact',
        'potion': 'Potion',
        'weak_skill': 'Weak Skill',
        'strong_skill': 'Strong Skill',
        'ultimate_skill': 'Ultimate Skill',
        'left_click': 'Left Click',
        'right_click': 'Right Click',
        'key_in_use': 'That key is already in use!',
        'already_in_town': 'You are already in town.',
    },
    ja: {
        // Auth
        'login_fail': 'ユーザー名またはパスワードが無効です。',
        'register_success': '登録が成功しました。ログインしてください。',
        'username_exists': 'ユーザー名はすでに存在します。',
        'enter_username_password': 'ユーザー名とパスワードの両方を入力してください。',

        // Game
        'job': '職業',
        'warrior': '戦士',
        'mage': '魔術師',
        'priest': '聖職者',
        'thief': '盗賊',
        'no_job': '無職',
        'level': 'レベル',
        'exp': '経験値',
        'hp': '体力',
        'mana': 'マナ',
        'ultimate': 'アルティメット',
        'gold': 'ゴールド',
        'potions': 'ポーション',
        'game_over': 'ゲームオーバー',
        'death_penalty': '倒れました！経験値の10%を失い、村に戻りました。',
        'no_mana': 'マナが足りません！',
        'no_ultimate': 'アルティメットゲージが溜まっていません！',
        'already_have_job': 'すでに職業に就いています。',
        'need_level_3_for_job': '転職するにはレベル3以上である必要があります。',
        'need_50_gold_for_job': '転職するには50ゴールドが必要です。',
        'job_change_complete': '転職完了！あなたは今\'{job}\'です！',
        'job_reset_confirm': '本当に50ゴールドを支払って職業をリセットしますか？',
        'job_reset_complete': '職業がリセットされました。',
        'need_job_for_skill': 'スキルを学ぶには、まず職業に就く必要があります。',
        'not_enough_gold': 'ゴールドが足りません。',
        'already_learned_skill': 'この種類のスキルはすでに習得しています。',
        'skill_learned': '\'{skillName}\'スキルを習得しました！',
        'no_potions': 'ポーションを持っていません。',
        'hp_full': 'HPはすでに満タンです！',
        'mana_full': 'マナはすでに満タンです！',
        'hp_and_mana_full': 'HPとマナは両方とも満タンです！',
        'use': '使用',
        'in_possession': '習得済み',
        'learn': '習得',
        'already_have_weapon': 'すでにこの職業の武器を所持しています。まず売却するか、別の武器を選択してください。',
        'job_restricted_item': 'このアイテムは「{job}」の職業のみが購入できます。',
        'item_purchased_attack_increase': '「{itemName}」を購入しました！攻撃力が{attack}増加しました。',
        'item_purchased': '「{itemName}」を購入しました！',

        // NPCs
        'merchant': '商人',
        'job_master': '転職マスター',
        'skill_master': 'スキルマスター',
        'reset_master': 'リセットマスター',

        // Portals
        'slime_dungeon': 'スライムの洞窟',
        'goblin_dungeon': 'ゴブリンの洞窟',
        'orc_dungeon': 'オークの洞窟',
        'subspecies_dungeon': '亜種の洞窟',
        'exit': '出口',

        // UI
        'settings': '設定',
        'keybinds': 'キー設定',
        'up': '上',
        'down': '下',
        'left': '左',
        'right': '右',
        'attack': '攻撃',
        'interact': 'インタラクト',
        'potion': 'ポーション',
        'weak_skill': '弱いスキル',
        'strong_skill': '強いスキル',
        'ultimate_skill': 'アルティメットスキル',
        'left_click': '左クリック',
        'right_click': '右クリック',
        'key_in_use': 'そのキーは既に使用されています！',
        'already_in_town': 'すでに町にいます。',
    }
};